name: CI/CD with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install and test
      run: |
        npm install
        npm test
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Convert repository name to lowercase
      id: repo_name_lowercase # Nadajemy ID temu krokowi, żeby móc odwołać się do jego wyjścia
      run: echo "LOWER_REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

    - name: Build Docker image
      # Używamy wyjścia z poprzedniego kroku, żeby uzyskać nazwę repozytorium małymi literami
      run: docker build -t ${{ steps.repo_name_lowercase.outputs.LOWER_REPO_NAME }}:${{ github.sha }} .

    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name test-container ${{ steps.repo_name_lowercase.outputs.LOWER_REPO_NAME }}:${{ github.sha }}
        sleep 20
        curl -f http://localhost:3000 || { echo "Aplikacja nie odpowiedziała na porcie 3000!"; exit 1; }
        docker stop test-container
        docker rm test-container
